### ISSUE TITLE
Create JWT authentification

### ISSUE THREAD

**Issue by Lordpluha** [NovaDevelopersCo/ecommerce-template#11]
# Todo
- [ ] Add AuthUser feature
- [ ] Set up JWT authentification functionality
- [ ] Configure auth with back
