### ISSUE TITLE
Module manufacturer

### ISSUE THREAD

**Issue by going-hi** [NovaDevelopersCo/ecommerce-template#25]
**Todo:**
- [x] Manufacturer schema
- [x] Manufactures module
- [x] fix notification modules
- [x] swagger base docs

After the merger #7 :
- [x] Add guard
- [x] replace upload file to upload with convert
- [x] update imports to imports with alies
- [x] finish findAll method with pagination
- [x] finish swagger docs
- [x] add method convertAndUpload in fileService 
- [x] put away Regex in constant
