### ISSUE TITLE
Module categories

### ISSUE THREAD

**Issue by going-hi** [NovaDevelopersCo/ecommerce-template#26]
**Todo:**
- [x] Category schema
- [x] Category module
- [x] swagger docs

After the merger #7 
- [ ] Add guard
- [ ] replace upload file to upload with convert
- [ ] update imports to imports with alies
- [ ] finish findAll method with pagination
- [ ] finish swagger docs
