### ISSUE TITLE
Finish product

### ISSUE THREAD

**Issue by going-hi** [NovaDevelopersCo/ecommerce-template#32]
**Todo:**
- [ ] swagger docs

After #26 
- [ ] add in schema categories
- [ ] intergrate filter by categories 
- [ ] All filter and sort product
