### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by going-hi** [NovaDevelopersCo/ecommerce-template#4]
**Todo**
- [x] User/ token schema
User:Token 1:1
![image](https://github.com/NovaDevelopersCo/ecommerce-template/assets/83702050/48306370-322c-44ad-bc27-c35236a57fb7)
![image](https://github.com/NovaDevelopersCo/ecommerce-template/assets/83702050/8fe003c4-5c9c-4590-b5c8-2f74e8558a48)
- [x] Abstract model
![image](https://github.com/NovaDevelopersCo/ecommerce-template/assets/83702050/a7c77bb6-beae-4cce-9745-79683c649de1)

- [x] method auth (refresh, logout, login, registration)
- [x] Decorators cookie, user
- [x]  access/refresh strategies
- [x] Guard access/refresh
- [x] Add swagger
- [x] Auth swagger docs
